### ISSUE TITLE
Kani doesn't work with Rust versions below 1.77

### ISSUE THREAD

**Issue by clubby789** [model-checking/kani#3967]
```sh
cargo +1.76 new demo
cd demo
cargo +1.76 kani
```

This results in the error
```
error: expected a version like "1.32"
error: Failed to execute cargo (exit status: 101). Found 0 compilation errors.
```

#3593 uses the package ID from `cargo metadata` as the argument to `-p`, but before the [package ID spec](https://doc.rust-lang.org/nightly/cargo/CHANGELOG.html#added-10) was stabilized in 1.77, the package ID couldn't be used in this way.

Feel free to close if supporting older Rust versions is not desired

**Comment by clubby789** [comment]
@carolynzech To elaborate on the issue above: While Kani mostly uses the linked nightly Rust toolchain, when gathering metadata we run `cargo metadata` which uses the system's rustup cargo shim. This respects any `+version` overrides, `rust-toolchain.toml` in the project directory etc. If rustup resolves to a pre-1.77 version of Cargo, this means we get a package identifier that has an invalid format for the `-p` argument leading to the above error.

**Comment by carolynzech** [comment]
I'm going to close this based on the conversation above.
