### PR TITLE
Do not inject macro overrides into external dependencies

### LINKED ISSUE #4665: `assert` is ambiguous (E0659) in dependencies that glob-import prelude macros (e.g. libc >= 0.2.188)
I tried this code (any crate depending on `libc >= 0.2.188`, published 2026-07-21; a plain `cargo new` with `libc = "0.2"` and any `#[kani::proof]` harness suffices):

```
cargo kani
```

with Kani version: `main` since #4643 (i.e. any version with the `#[macro_use]` macro-override injection).

I expected to see this happen: the crate compiles and the harness is verified.

Instead, this happened: compilation of `libc` fails with dozens of

```
error[E0659]: `assert` is ambiguous
  --> .../libc-0.2.188/src/types.rs:73:5
   |
73 |     assert!(size_of::<u16>() <= size_of::<c_short>()); // Should always be true
   |     ^^^^^^ ambiguous name
   |
   = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
note: `assert` could refer to the macro imported here [--> libc's `use crate::prelude::*;`]
note: `assert` could also refer to the macro imported here [--> <kani_macro_overrides>]
```

**Root cause:** since #4643, kani-compiler injects `#[macro_use] extern crate std as _kani_std_macros;` into every `std` crate it compiles, placing Kani's `assert!`/`panic!`/… overrides in the macro_use-prelude scope. That scope shadows the standard prelude silently (intended), but is *ambiguous* (E0659) against an explicit glob import of the same macro name. libc's internal prelude does `pub(crate) use core::{assert, ...}` and its modules `use crate::prelude::*` — harmless until libc 0.2.188 added `assert!` calls in such a module (`src/types.rs` type-size sanity checks). Any user whose lockfile resolves libc ≥ 0.2.188 is affected; Kani's own CI regression suites fail on every PR for the same reason (the test manifests use a floating `libc = "0.2"`; pushes to `main` still pass only because their last dependency resolution predates the libc release).

Fix in preparation: only inject the overrides into local crates, not external (registry/git) dependencies, using `Session::opts.lint_cap` as the discriminator (cargo passes `--cap-lints allow` exactly for non-local dependencies). External dependencies then use the real `assert!`/`panic!` macros, which Kani models soundly — consistent with `no_std` dependencies, which never had the overrides. Local path/workspace dependencies keep the overrides (as pinned by the `assert-reach` and `stubbing-ws-packages` tests).

### PR DESCRIPTION
**Pull request by tautschnig**
Since libc 0.2.188 was published (2026-07-21 09:38 UTC), every crate graph containing it fails to compile under Kani with dozens of ``error[E0659]: `assert` is ambiguous`` errors — including Kani's own `regression` and `perf` CI jobs on every PR (the cargo-kani test manifests use a floating `libc = "0.2"`; pushes to `main` still pass only because their last dependency resolution predates the release). See #4665 for the full analysis.

**Root cause:** the macro-override injection introduced in #4643 (`#[macro_use] extern crate std as _kani_std_macros;`) puts Kani's `assert!`/`panic!`/… overrides in the macro_use-prelude scope of every `std` crate kani-compiler builds. That scope shadows the standard prelude silently (intended), but is *ambiguous* (E0659) against an explicit glob import of the same macro name. libc's internal prelude re-exports `core::assert` and its modules glob-import that prelude; libc 0.2.188 added `assert!` calls in such a module (type-size sanity checks in `src/types.rs`), turning the latent conflict into a hard error.

**Fix:** restrict the injection to local crates. Cargo passes `--cap-lints allow` exactly for non-local (registry/git) dependencies, so `Session::opts.lint_cap` is the discriminator. External dependencies then use the real `assert!`/`panic!`/… macros, which Kani models soundly — consistent with `no_std` dependencies, which never had the overrides. Local path/workspace dependencies and standalone `kani` builds keep the overrides, preserving the dependency reachability/message behavior pinned by the `assert-reach` and `stubbing-ws-packages` tests.

**Testing:**
* The existing `cargo-kani/libc` test acts as the regression test: with libc 0.2.188 it fails before this change and passes after (its floating version requirement is a feature — it surfaced this bug within hours of the libc release). I first prototyped a hermetic path-dependency reproducer, but local path deps *should* keep the overrides (as `assert-reach`/`stubbing-ws-packages` demonstrate), so the libc test is the accurate coverage.
* Full `cargo-kani` suite: 71 passed / 0 failed, including the five tests failing in CI today (`libc`, `chrono_dep`, `dependencies`, `cbmc-unknown-lang-mode`, `stubbing-validate-random`) and the two that pin local-dependency semantics.
* `expected/assert*` standalone tests pass (override still active outside cargo).

An earlier iteration used `CARGO_PRIMARY_PACKAGE` as the discriminator, but that also strips the overrides from workspace/path dependencies, breaking `assert-reach` and `stubbing-ws-packages`; `lint_cap` matches the desired local/external cut exactly.

Resolves #4665

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT licenses.

### CODE REVIEW

**Comment by tautschnig** [comment]
The compiler benchmarks need #4664, but those are not marked "Required" so we'll need to get the changes in this PR merged first.

**Review by feliperodri — APPROVED** [review]
